In [5]:
import sys
print(sys.executable)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python310\python.exe


In [7]:
import torch

x=torch.tensor([1.0,2.0,3.0,4.0])

print(x.shape)

r=torch.rand(2,3)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = x.to(device)

torch.Size([4])


In [8]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(torch.dot(a,b))

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor(32)


In [9]:
x=torch.tensor(2.0, requires_grad=True)
y=x**2+3*x
y.backward()
print(x.grad)

tensor(7.)
