Problem 1 — Tensor Basics

Create a tensor [1,2,3,4,5] and:

Print shape
Convert to float
Move it to GPU (if available)

In [2]:
import torch 
x=torch.tensor([1,2,3,4,5])

print(x.shape)

r=torch.rand(2,3)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = x.to(device)

torch.Size([5])


Problem 2 — Operations

Do:

Addition
Element-wise multiplication
Dot product

In [3]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

print(a+b)
print(a*b)
print(torch.dot(a,b))

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


Problem 3 — Reshape

Create tensor [1,2,3,4,5,6] and reshape to:

(2,3)
(3,2)

In [6]:
import torch

x = torch.tensor([1,2,3,4,5,6])  # correct

x1 = x.reshape(2,3)
print(x1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
import torch

x = torch.tensor([1,2,3,4,5,6])  # correct

x1 = x.reshape(3,2)
print(x1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


Problem 4 — Autograd

In [9]:
x = torch.tensor(4.0, requires_grad=True)

y=x**3+2*x
y.backward()
print(x.grad)

tensor(50.)
